openapi: 3.0.0
info:
  version: 1.0.0
  title: MY_TITLE
  description: 스웨거 실습 테스트
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jwscript/SWAGGER_TEST/1.0.0
  - description: Google API
    url: https://www.google.com
paths:
  /complete/search:
    get:
      summary: 자동완성 검색 결과를 반환합니다.
      parameters:
        - name: q
          in: query
          schema:
            type: string
        - name: client
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A Text File
          content:
            text/plain:
              schema:
                type: string